### ISSUE TITLE
how to compute NP VP PP rate of Aggregate-level or Instance-level CTER?

### ISSUE THREAD

**Issue by leileilin** [yafuly/CoGnition#4]
Hi, thanks for so wonderful work for open source.

**Comment by yafuly** [comment]
Hi,

Please refer to `eval/eval.py' for computing aggregate-level and instance-level CTER. As for CTER for each subset (i.e., NP, VP, and PP), basically evaluate the model results on each of these subsets by computing CTER accordingly.

**Comment by leileilin** [comment]
> Hi,
> 
> Please refer to `eval/eval.py' for computing aggregate-level and instance-level CTER. As for CTER for each subset (i.e., NP, VP, and PP), basically evaluate the model results on each of these subsets by computing CTER accordingly.

I want to know how to get the subsets(i.e., NP, VP, and PP)?

**Comment by leileilin** [comment]
> Hi,
> 
> Please refer to `eval/eval.py' for computing aggregate-level and instance-level CTER. As for CTER for each subset (i.e., NP, VP, and PP), basically evaluate the model results on each of these subsets by computing CTER accordingly.

sorry, i find in the `data`
